### PR TITLE
Fix inaccurate presence

### LINKED ISSUE #30: Online/Offline status is inaccurate
I have not yet found a pattern. But I noticed some inconsistencies about users being shown as online and offline.

This only happens if someone registered as 'online' when i was online. And then they are not shown as offline even when they are logged out.

People who sent me messages while I was offline do not register as 'online' when they are logged off and I came online after they logged off.

### PR DESCRIPTION
**Pull request by LEDfan**
Fixes #30 
Refs #19 
TODO
 - [x] add tests for https://github.com/nextcloud/jsxc.nextcloud/pull/32/commits/5a8a5d06bd8fd6691ecd983ab9fe8ad2a4014c84

### CODE REVIEW

File: lib/db/presencemapper.php [hunk 1]
```diff
@@ -152,12 +162,12 @@ public function setActive($user) {
 	 * contacted the server for $this->timeout seconds.
 	 */
 	public function updatePresence() {
-		if (!self::$updatedPresense) {
```
Comment (MarcelWaldvogel) [inline lib/db/presencemapper.php]: Ouch, that's horrible to find :wink:

Comment (sualko) [inline lib/db/presencemapper.php]: I think it was just an typo, see line 25.
